// Lebensmittel-Datenbank (aus Keto_Rechner_Final.xlsx, 105 Einträge)
// Alle Nährwerte beziehen sich auf 100 g.
const FOODS_DEFAULT = [
  {"kategorie": "Eier", "name": "Hühnerei, Vollei, frisch", "pro": 100, "eiweiss": 12.9, "fett": 11.2, "kh": 0.7, "cholesterin": 396, "natrium": 144, "ballaststoffe": 0},
  {"kategorie": "Fett", "name": "Butter", "pro": 100, "eiweiss": 0.67, "fett": 83.2, "kh": 0, "cholesterin": 240, "natrium": 5, "ballaststoffe": 0},
  {"kategorie": "Fett", "name": "Margarine (pflanzlich)", "pro": 100, "eiweiss": 0.2, "fett": 80, "kh": 0.4, "cholesterin": 7, "natrium": 101, "ballaststoffe": 0},
  {"kategorie": "Fett", "name": "Schweineschmalz", "pro": 100, "eiweiss": 0.1, "fett": 99.7, "kh": 0, "cholesterin": 86, "natrium": 1, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Forelle, gegart", "pro": 100, "eiweiss": 23.84, "fett": 2.9, "kh": 0, "cholesterin": 69, "natrium": 58, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Forelle, geräuchert", "pro": 100, "eiweiss": 21.7, "fett": 2, "kh": 0, "cholesterin": 59, "natrium": 67, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Garnelen", "pro": 100, "eiweiss": 14.6, "fett": 0.9, "kh": 0, "cholesterin": 140, "natrium": 500, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Heilbutt, gegart", "pro": 100, "eiweiss": 23.27, "fett": 2.03, "kh": 0, "cholesterin": 38, "natrium": 96, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Makrele, geräuchert", "pro": 100, "eiweiss": 20.1, "fett": 16, "kh": 0, "cholesterin": 80, "natrium": 100, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Rotbarsch, gegart", "pro": 100, "eiweiss": 21.53, "fett": 4.3, "kh": 0, "cholesterin": 50, "natrium": 91, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Räucherlachs", "pro": 100, "eiweiss": 19.5, "fett": 6.7, "kh": 1, "cholesterin": 60, "natrium": 53, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Sardine in der Dose in Öl", "pro": 100, "eiweiss": 24, "fett": 12.9, "kh": 0, "cholesterin": 14, "natrium": 270, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Scholle, gegart", "pro": 100, "eiweiss": 20.8, "fett": 2.27, "kh": 0, "cholesterin": 50, "natrium": 119, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Thunfisch in der Dose in Öl", "pro": 100, "eiweiss": 21.5, "fett": 15.5, "kh": 0, "cholesterin": 69, "natrium": 841, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Corned beef", "pro": 100, "eiweiss": 21.7, "fett": 6, "kh": 0, "cholesterin": 70, "natrium": 833, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Hähnchenbrust ohne Haut", "pro": 100, "eiweiss": 23.55, "fett": 0.7, "kh": 0, "cholesterin": 66, "natrium": 72, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Kochschinken", "pro": 100, "eiweiss": 18.43, "fett": 3.85, "kh": 0.96, "cholesterin": 49, "natrium": 942, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Lachsschinken (geräuchert)", "pro": 100, "eiweiss": 18.28, "fett": 4.36, "kh": 0.89, "cholesterin": 51, "natrium": 2473, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Putenbrust ohne Haut", "pro": 100, "eiweiss": 21.1, "fett": 1, "kh": 0, "cholesterin": 60, "natrium": 46, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Rinderhackfleisch", "pro": 100, "eiweiss": 22.5, "fett": 14, "kh": 0.45, "cholesterin": 58, "natrium": 60, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Schweinefilet", "pro": 100, "eiweiss": 22, "fett": 2, "kh": 0, "cholesterin": 70, "natrium": 74, "ballaststoffe": 0},
  {"kategorie": "GEMÜSE", "name": "Avocado", "pro": 100, "eiweiss": 1.9, "fett": 23.5, "kh": 0.4, "cholesterin": 0, "natrium": 3, "ballaststoffe": 6.3},
  {"kategorie": "GEMÜSE", "name": "Blumenkohl, gekocht", "pro": 100, "eiweiss": 2.1, "fett": 0.2, "kh": 2, "cholesterin": 0, "natrium": 11, "ballaststoffe": 2},
  {"kategorie": "GEMÜSE", "name": "Broccoli, gekocht", "pro": 100, "eiweiss": 2.8, "fett": 0.2, "kh": 2.5, "cholesterin": 0, "natrium": 9, "ballaststoffe": 2.7},
  {"kategorie": "GEMÜSE", "name": "Champignon (Zucht-)", "pro": 100, "eiweiss": 2.7, "fett": 0.2, "kh": 0.6, "cholesterin": 0, "natrium": 8, "ballaststoffe": 2},
  {"kategorie": "GEMÜSE", "name": "Chinakohl", "pro": 100, "eiweiss": 1.2, "fett": 0.3, "kh": 1.2, "cholesterin": 0, "natrium": 19, "ballaststoffe": 1.9},
  {"kategorie": "GEMÜSE", "name": "Essiggurke", "pro": 100, "eiweiss": 1, "fett": 0.2, "kh": 3.8, "cholesterin": 0, "natrium": 960, "ballaststoffe": 0.29},
  {"kategorie": "GEMÜSE", "name": "Fenchel, roh", "pro": 100, "eiweiss": 2.4, "fett": 0.3, "kh": 2.8, "cholesterin": 0, "natrium": 86, "ballaststoffe": 4.2},
  {"kategorie": "GEMÜSE", "name": "Gartenkresse, roh", "pro": 100, "eiweiss": 4.2, "fett": 0.7, "kh": 2.5, "cholesterin": 0, "natrium": 5, "ballaststoffe": 3.5},
  {"kategorie": "GEMÜSE", "name": "Grünkohl, roh", "pro": 100, "eiweiss": 4.3, "fett": 0.9, "kh": 2.5, "cholesterin": 0, "natrium": 44, "ballaststoffe": 4.2},
  {"kategorie": "GEMÜSE", "name": "Gurke, roh", "pro": 100, "eiweiss": 0.6, "fett": 0.2, "kh": 1.81, "cholesterin": 0, "natrium": 3, "ballaststoffe": 0.54},
  {"kategorie": "GEMÜSE", "name": "Knollensellerie, gekocht", "pro": 100, "eiweiss": 1.4, "fett": 0.3, "kh": 2.8, "cholesterin": 0, "natrium": 60, "ballaststoffe": 4.2},
  {"kategorie": "GEMÜSE", "name": "Kopfsalat", "pro": 100, "eiweiss": 1.22, "fett": 0.22, "kh": 1.06, "cholesterin": 0, "natrium": 7.5, "ballaststoffe": 1.44},
  {"kategorie": "GEMÜSE", "name": "Lauch", "pro": 100, "eiweiss": 2.2, "fett": 0.3, "kh": 3.2, "cholesterin": 0, "natrium": 4, "ballaststoffe": 2.3},
  {"kategorie": "GEMÜSE", "name": "Möhren roh", "pro": 100, "eiweiss": 0.98, "fett": 0.2, "kh": 4.8, "cholesterin": 0, "natrium": 60, "ballaststoffe": 3.63},
  {"kategorie": "GEMÜSE", "name": "Möhren, gekocht", "pro": 100, "eiweiss": 0.8, "fett": 0.2, "kh": 3.1, "cholesterin": 0, "natrium": 42, "ballaststoffe": 2.5},
  {"kategorie": "GEMÜSE", "name": "Radieschen, roh", "pro": 100, "eiweiss": 1.1, "fett": 0.1, "kh": 2, "cholesterin": 0, "natrium": 17, "ballaststoffe": 1.6},
  {"kategorie": "GEMÜSE", "name": "Rettich, roh", "pro": 100, "eiweiss": 1, "fett": 0.2, "kh": 1.9, "cholesterin": 0, "natrium": 18, "ballaststoffe": 1.5},
  {"kategorie": "GEMÜSE", "name": "Rosenkohl, gekocht", "pro": 100, "eiweiss": 3.8, "fett": 0.5, "kh": 2.4, "cholesterin": 0, "natrium": 5, "ballaststoffe": 4},
  {"kategorie": "GEMÜSE", "name": "Rote Beete, gekocht", "pro": 100, "eiweiss": 1.1, "fett": 0.1, "kh": 5, "cholesterin": 0, "natrium": 48, "ballaststoffe": 2},
  {"kategorie": "GEMÜSE", "name": "Rotkohl, roh", "pro": 100, "eiweiss": 1.5, "fett": 0.2, "kh": 3.2, "cholesterin": 0, "natrium": 4, "ballaststoffe": 2.5},
  {"kategorie": "GEMÜSE", "name": "Sauerkraut, abgetropft roh", "pro": 100, "eiweiss": 1.5, "fett": 0.3, "kh": 0.8, "cholesterin": 0, "natrium": 355, "ballaststoffe": 2.2},
  {"kategorie": "GEMÜSE", "name": "Spinat", "pro": 100, "eiweiss": 2.52, "fett": 0.3, "kh": 0.55, "cholesterin": 0, "natrium": 65, "ballaststoffe": 2.58},
  {"kategorie": "GEMÜSE", "name": "Staudensellerie, roh", "pro": 100, "eiweiss": 1.2, "fett": 0.2, "kh": 2.18, "cholesterin": 0, "natrium": 132, "ballaststoffe": 2.54},
  {"kategorie": "GEMÜSE", "name": "Tomaten, roh", "pro": 100, "eiweiss": 0.95, "fett": 0.21, "kh": 2.6, "cholesterin": 0, "natrium": 3, "ballaststoffe": 1},
  {"kategorie": "GEMÜSE", "name": "Zucchini", "pro": 100, "eiweiss": 1.89, "fett": 0.29, "kh": 2.26, "cholesterin": 0, "natrium": 3, "ballaststoffe": 1.1},
  {"kategorie": "GEMÜSE", "name": "Zwiebel, roh", "pro": 100, "eiweiss": 1.18, "fett": 0.25, "kh": 4.92, "cholesterin": 0, "natrium": 3, "ballaststoffe": 1.8},
  {"kategorie": "Getreide", "name": "Bulgur", "pro": 100, "eiweiss": 12.6, "fett": 2, "kh": 73.4, "cholesterin": 0, "natrium": 10, "ballaststoffe": 2},
  {"kategorie": "Getreide", "name": "Knisterbrot", "pro": 100, "eiweiss": 12, "fett": 4, "kh": 73, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Getreide", "name": "Pasta, eifrei", "pro": 100, "eiweiss": 12.5, "fett": 1.2, "kh": 70.45, "cholesterin": 0, "natrium": 5, "ballaststoffe": 5.1},
  {"kategorie": "Getreide", "name": "Reis", "pro": 100, "eiweiss": 7, "fett": 2, "kh": 75, "cholesterin": 0, "natrium": 10, "ballaststoffe": 2},
  {"kategorie": "Getreide", "name": "Semmelbrösel", "pro": 100, "eiweiss": 10.1, "fett": 2.1, "kh": 73.51, "cholesterin": 0, "natrium": 400, "ballaststoffe": 5.3},
  {"kategorie": "Getreide", "name": "Vollkornbrot", "pro": 100, "eiweiss": 6.5, "fett": 2, "kh": 36, "cholesterin": 0, "natrium": 430, "ballaststoffe": 8.7},
  {"kategorie": "Gewürze", "name": "Mayonnaise 80 % Fett", "pro": 100, "eiweiss": 1.49, "fett": 82.5, "kh": 2, "cholesterin": 237, "natrium": 481, "ballaststoffe": 0},
  {"kategorie": "Gewürze", "name": "Remoulade 65 % Fett", "pro": 100, "eiweiss": 1, "fett": 75, "kh": 3, "cholesterin": 100, "natrium": 265, "ballaststoffe": 0.5},
  {"kategorie": "Gewürze", "name": "Salz", "pro": 100, "eiweiss": 0, "fett": 0, "kh": 0, "cholesterin": 0, "natrium": 38850, "ballaststoffe": 0},
  {"kategorie": "Gewürze", "name": "Senf, scharf", "pro": 100, "eiweiss": 6, "fett": 4, "kh": 6, "cholesterin": 0, "natrium": 1250, "ballaststoffe": 1},
  {"kategorie": "Gewürze", "name": "Tomatenmark", "pro": 100, "eiweiss": 2.3, "fett": 0.5, "kh": 5.5, "cholesterin": 0, "natrium": 240, "ballaststoffe": 2.8},
  {"kategorie": "Käse", "name": "Appenzeller Rahmstufe (50 %)", "pro": 100, "eiweiss": 25.4, "fett": 31.6, "kh": 0, "cholesterin": 74, "natrium": 600, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Brie Rahmstufe (50 %)", "pro": 100, "eiweiss": 21.1, "fett": 27.9, "kh": 0.01, "cholesterin": 92, "natrium": 700, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Camembert 30 %", "pro": 100, "eiweiss": 23, "fett": 0.4, "kh": 13, "cholesterin": 46, "natrium": 700, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Feta", "pro": 100, "eiweiss": 17, "fett": 18.8, "kh": 0, "cholesterin": 45, "natrium": 1300, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Frischkäse Arla 17% absolut", "pro": 100, "eiweiss": 8.5, "fett": 16.7, "kh": 3, "cholesterin": 51, "natrium": 84, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Frischkäse Doppelrahmstufe", "pro": 100, "eiweiss": 11, "fett": 31.5, "kh": 2.5, "cholesterin": 103, "natrium": 350, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Harzer Käse mager", "pro": 100, "eiweiss": 30, "fett": 0.5, "kh": 0, "cholesterin": 3, "natrium": 800, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Mozzarella", "pro": 100, "eiweiss": 18, "fett": 20, "kh": 2, "cholesterin": 78, "natrium": 373, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Parmesan", "pro": 100, "eiweiss": 35.6, "fett": 25.8, "kh": 0.06, "cholesterin": 68, "natrium": 704, "ballaststoffe": 0},
  {"kategorie": "Käse", "name": "Schmelzkäse Doppelrahmstufe (60 %)", "pro": 100, "eiweiss": 13.2, "fett": 30.4, "kh": 0.9, "cholesterin": 85, "natrium": 1100, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Creme Double 42 % Fett", "pro": 100, "eiweiss": 2.2, "fett": 42, "kh": 3.2, "cholesterin": 126, "natrium": 30, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Creme Fraiche 30 % Fett", "pro": 100, "eiweiss": 2.7, "fett": 30.2, "kh": 3.7, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Joghurt 3,5 % Fett", "pro": 100, "eiweiss": 3.9, "fett": 3.5, "kh": 4.6, "cholesterin": 13, "natrium": 50, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Kuhmilch 3,5 % Fett", "pro": 100, "eiweiss": 3.3, "fett": 3.5, "kh": 4.76, "cholesterin": 13, "natrium": 50, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "LC1 natur 3,5 % Fett", "pro": 100, "eiweiss": 4.7, "fett": 3.5, "kh": 5.6, "cholesterin": 13, "natrium": 0.07, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Saure Sahne, 10 % Fett", "pro": 100, "eiweiss": 3.1, "fett": 10, "kh": 3.3, "cholesterin": 37, "natrium": 40, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Schlagsahne 30 % Fett", "pro": 100, "eiweiss": 2.5, "fett": 30, "kh": 3.2, "cholesterin": 90, "natrium": 30, "ballaststoffe": 0},
  {"kategorie": "Nüsse", "name": "Macadamianüsse, ungesalzen", "pro": 100, "eiweiss": 7.5, "fett": 73, "kh": 0, "cholesterin": 0, "natrium": 5, "ballaststoffe": 15.4},
  {"kategorie": "Nüsse", "name": "Paranüsse", "pro": 100, "eiweiss": 13.59, "fett": 66.8, "kh": 3.55, "cholesterin": 0, "natrium": 2, "ballaststoffe": 8.1},
  {"kategorie": "Nüsse", "name": "Pecannüsse", "pro": 100, "eiweiss": 9.3, "fett": 72, "kh": 4.44, "cholesterin": 0, "natrium": 3, "ballaststoffe": 9.46},
  {"kategorie": "Nüsse", "name": "Walnusskerne", "pro": 100, "eiweiss": 14.4, "fett": 62.5, "kh": 10.6, "cholesterin": 0, "natrium": 2, "ballaststoffe": 6.14},
  {"kategorie": "Obst", "name": "Apfel", "pro": 100, "eiweiss": 0.34, "fett": 0.4, "kh": 11.43, "cholesterin": 0, "natrium": 3, "ballaststoffe": 2},
  {"kategorie": "Obst", "name": "Aprikose", "pro": 100, "eiweiss": 0.9, "fett": 0.1, "kh": 8.54, "cholesterin": 0, "natrium": 2, "ballaststoffe": 1.9},
  {"kategorie": "Obst", "name": "Beerenobst", "pro": 100, "eiweiss": 0.82, "fett": 0.4, "kh": 5.51, "cholesterin": 0, "natrium": 2, "ballaststoffe": 1.63},
  {"kategorie": "Obst", "name": "Birne", "pro": 100, "eiweiss": 0.5, "fett": 0.3, "kh": 12.4, "cholesterin": 0, "natrium": 2, "ballaststoffe": 2.8},
  {"kategorie": "Obst", "name": "Erbeeren", "pro": 100, "eiweiss": 0.82, "fett": 0.4, "kh": 5.51, "cholesterin": 0, "natrium": 3, "ballaststoffe": 1.63},
  {"kategorie": "Obst", "name": "Grapefruit", "pro": 100, "eiweiss": 0.6, "fett": 0.15, "kh": 8.95, "cholesterin": 0, "natrium": 2, "ballaststoffe": 0.58},
  {"kategorie": "Obst", "name": "Heidelbeeren", "pro": 100, "eiweiss": 0.6, "fett": 0.6, "kh": 7.4, "cholesterin": 0, "natrium": 1, "ballaststoffe": 4.9},
  {"kategorie": "Obst", "name": "Himbeere", "pro": 100, "eiweiss": 1.3, "fett": 0.3, "kh": 4.8, "cholesterin": 0, "natrium": 1, "ballaststoffe": 6.7},
  {"kategorie": "Obst", "name": "Kirschen, sauer", "pro": 100, "eiweiss": 0.9, "fett": 0.4, "kh": 11, "cholesterin": 0, "natrium": 2, "ballaststoffe": 1.04},
  {"kategorie": "Obst", "name": "Kirschen, süß", "pro": 100, "eiweiss": 0.9, "fett": 0.3, "kh": 13.3, "cholesterin": 0, "natrium": 3, "ballaststoffe": 1.5},
  {"kategorie": "Obst", "name": "Kiwi", "pro": 100, "eiweiss": 1, "fett": 0.63, "kh": 10.77, "cholesterin": 0, "natrium": 4, "ballaststoffe": 3.9},
  {"kategorie": "Obst", "name": "Nektarine", "pro": 100, "eiweiss": 0.9, "fett": 0.1, "kh": 12.4, "cholesterin": 0, "natrium": 9, "ballaststoffe": 2.2},
  {"kategorie": "Obst", "name": "Orange", "pro": 100, "eiweiss": 1, "fett": 0.2, "kh": 9.19, "cholesterin": 0, "natrium": 1, "ballaststoffe": 2.2},
  {"kategorie": "Obst", "name": "Papaya", "pro": 100, "eiweiss": 0.52, "fett": 0.09, "kh": 2.4, "cholesterin": 0, "natrium": 3, "ballaststoffe": 1.9},
  {"kategorie": "Obst", "name": "Pfirsich", "pro": 100, "eiweiss": 0.7, "fett": 0.3, "kh": 15.6, "cholesterin": 0, "natrium": 1, "ballaststoffe": 0.8},
  {"kategorie": "Tofu", "name": "Tofu fest", "pro": 100, "eiweiss": 15.8, "fett": 8.7, "kh": 0.6, "cholesterin": 0, "natrium": 7, "ballaststoffe": 0.6},
  {"kategorie": "Wurst", "name": "Blutwurst (Rotwurst)", "pro": 100, "eiweiss": 20.15, "fett": 10.24, "kh": 0.22, "cholesterin": 81, "natrium": 711, "ballaststoffe": 0.04},
  {"kategorie": "Wurst", "name": "Frühstücksspeck", "pro": 100, "eiweiss": 17.49, "fett": 7.94, "kh": 0.85, "cholesterin": 49, "natrium": 2366, "ballaststoffe": 0},
  {"kategorie": "Wurst", "name": "Leberkäse", "pro": 100, "eiweiss": 13.04, "fett": 27.15, "kh": 0.59, "cholesterin": 77, "natrium": 710, "ballaststoffe": 0.09},
  {"kategorie": "Wurst", "name": "Leberwurst", "pro": 100, "eiweiss": 15.23, "fett": 29.43, "kh": 1.46, "cholesterin": 160, "natrium": 663, "ballaststoffe": 0},
  {"kategorie": "Wurst", "name": "Salami", "pro": 100, "eiweiss": 19.84, "fett": 32.12, "kh": 0.22, "cholesterin": 76, "natrium": 1251, "ballaststoffe": 0.06},
  {"kategorie": "Wurst", "name": "Schweinsbratwurst", "pro": 100, "eiweiss": 16.26, "fett": 27.82, "kh": 0.29, "cholesterin": 62, "natrium": 693, "ballaststoffe": 0.05},
  {"kategorie": "Wurst", "name": "Wiener Würstchen", "pro": 100, "eiweiss": 14.36, "fett": 27.69, "kh": 0.19, "cholesterin": 57, "natrium": 838, "ballaststoffe": 0.05},
  {"kategorie": "Öle", "name": "Olivenöl", "pro": 100, "eiweiss": 0, "fett": 100, "kh": 0, "cholesterin": 1, "natrium": 1, "ballaststoffe": 0},
  {"kategorie": "Öle", "name": "Rapsöl", "pro": 100, "eiweiss": 0, "fett": 100, "kh": 0, "cholesterin": 2.1, "natrium": 1, "ballaststoffe": 0},
  {"kategorie": "Öle", "name": "Walnussöl", "pro": 100, "eiweiss": 0, "fett": 92, "kh": 0, "cholesterin": 2, "natrium": 1, "ballaststoffe": 0},
  // --- Zutaten aus den Sondennahrungs-Rezepten (Werte laut Arbeitsblatt) ---
  {"kategorie": "Sonde / Spezial", "name": "KetoCal 3:1", "pro": 100, "eiweiss": 15.4, "fett": 68.6, "kh": 7.2, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Sonde / Spezial", "name": "Johannisbrotkernmehl", "pro": 100, "eiweiss": 4.5, "fett": 1.4, "kh": 7.3, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Sonde / Spezial", "name": "Himmeltau Grießbrei", "pro": 100, "eiweiss": 10, "fett": 0.9, "kh": 68, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Sonstiges", "name": "Wasser", "pro": 100, "eiweiss": 0, "fett": 0, "kh": 0, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Obst", "name": "Banane roh", "pro": 100, "eiweiss": 1, "fett": 0.2, "kh": 20, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Obst", "name": "Apfelmus ohne Zuckerzusatz", "pro": 100, "eiweiss": 0.2, "fett": 0.1, "kh": 19.2, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Hühnerbrust ohne Haut", "pro": 100, "eiweiss": 22.8, "fett": 0.9, "kh": 0, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "GEMÜSE", "name": "Zucchini roh", "pro": 100, "eiweiss": 1.6, "fett": 0.4, "kh": 2.2, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "GEMÜSE", "name": "Zucchini gegart", "pro": 100, "eiweiss": 2.1, "fett": 0.3, "kh": 2.4, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "GEMÜSE", "name": "Kartoffel gekocht", "pro": 100, "eiweiss": 2, "fett": 0.1, "kh": 14.8, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "GEMÜSE", "name": "Karotte", "pro": 100, "eiweiss": 1.1, "fett": 0.2, "kh": 4.8, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Milchprod.", "name": "Schlagobers (NÖM)", "pro": 100, "eiweiss": 2.3, "fett": 36, "kh": 3, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0}
];
