// Lebensmittel-Datenbank (Diätologen-Liste, österreichisch) + wenige Zusätze für Rezepte.
// Alle Nährwerte pro 100 g.
const FOODS_DEFAULT = [
  {"kategorie": "Gemüse", "name": "Avocado", "pro": 100, "eiweiss": 1.9, "fett": 23.5, "kh": 0.4, "cholesterin": 0.0, "natrium": 3.0, "ballaststoffe": 6.3},
  {"kategorie": "Gemüse", "name": "Erbsen grün, roh und TK", "pro": 100, "eiweiss": 5.8, "fett": 0.5, "kh": 10.6, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Karfiol roh", "pro": 100, "eiweiss": 2.4, "fett": 0.3, "kh": 2.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Karfiol gekocht", "pro": 100, "eiweiss": 2.1, "fett": 0.2, "kh": 2.0, "cholesterin": 0.0, "natrium": 11.0, "ballaststoffe": 2.0},
  {"kategorie": "Gemüse", "name": "Broccoli, roh oder TK", "pro": 100, "eiweiss": 3.3, "fett": 0.2, "kh": 2.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Broccoli, gekocht", "pro": 100, "eiweiss": 2.8, "fett": 0.2, "kh": 2.0, "cholesterin": 0.0, "natrium": 9.0, "ballaststoffe": 2.7},
  {"kategorie": "Gemüse", "name": "Chicorée roh", "pro": 100, "eiweiss": 1.3, "fett": 0.2, "kh": 2.3, "cholesterin": 0.0, "natrium": 4.0, "ballaststoffe": 1.3},
  {"kategorie": "Gemüse", "name": "Chinakohl roh", "pro": 100, "eiweiss": 1.2, "fett": 0.3, "kh": 1.2, "cholesterin": 0.0, "natrium": 19.0, "ballaststoffe": 1.9},
  {"kategorie": "Gemüse", "name": "Cremespinat IGLO", "pro": 100, "eiweiss": 3.3, "fett": 3.2, "kh": 2.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Endivien roh", "pro": 100, "eiweiss": 1.8, "fett": 0.2, "kh": 0.3, "cholesterin": 0.0, "natrium": 53.0, "ballaststoffe": 1.2},
  {"kategorie": "Gemüse", "name": "Essiggurkerl mit Süßstoff zubereitet", "pro": 100, "eiweiss": 1.0, "fett": 0.2, "kh": 3.8, "cholesterin": 0.0, "natrium": 960.0, "ballaststoffe": 0.4},
  {"kategorie": "Gemüse", "name": "Feldsalat roh", "pro": 100, "eiweiss": 1.8, "fett": 0.4, "kh": 0.7, "cholesterin": 0.0, "natrium": 4.0, "ballaststoffe": 1.5},
  {"kategorie": "Gemüse", "name": "Frühlingszwiebeln frisch", "pro": 100, "eiweiss": 0.9, "fett": 0.3, "kh": 8.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Fenchel, roh", "pro": 100, "eiweiss": 2.4, "fett": 0.3, "kh": 2.8, "cholesterin": 0.0, "natrium": 86.0, "ballaststoffe": 4.2},
  {"kategorie": "Gemüse", "name": "Gartenkresse, roh", "pro": 100, "eiweiss": 4.2, "fett": 0.7, "kh": 2.5, "cholesterin": 0.0, "natrium": 5.0, "ballaststoffe": 3.5},
  {"kategorie": "Gemüse", "name": "Grüne Bohnen (Fisolen) roh", "pro": 100, "eiweiss": 2.4, "fett": 0.2, "kh": 5.1, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Grünkohl roh", "pro": 100, "eiweiss": 4.3, "fett": 0.9, "kh": 2.5, "cholesterin": 0.0, "natrium": 44.0, "ballaststoffe": 4.2},
  {"kategorie": "Gemüse", "name": "Grüner Salat roh", "pro": 100, "eiweiss": 1.3, "fett": 0.2, "kh": 1.1, "cholesterin": 0.0, "natrium": 8.0, "ballaststoffe": 1.4},
  {"kategorie": "Gemüse", "name": "Kartoffel gekocht", "pro": 100, "eiweiss": 2.0, "fett": 0.1, "kh": 14.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Knollensellerie, gekocht", "pro": 100, "eiweiss": 1.4, "fett": 0.3, "kh": 2.8, "cholesterin": 0.0, "natrium": 60.0, "ballaststoffe": 4.0},
  {"kategorie": "Gemüse", "name": "Lauch roh", "pro": 100, "eiweiss": 2.2, "fett": 0.3, "kh": 3.2, "cholesterin": 0.0, "natrium": 5.0, "ballaststoffe": 2.3},
  {"kategorie": "Gemüse", "name": "Mais", "pro": 100, "eiweiss": 2.5, "fett": 1.2, "kh": 11.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Mangold roh", "pro": 100, "eiweiss": 2.1, "fett": 0.3, "kh": 0.7, "cholesterin": 0.0, "natrium": 90.0, "ballaststoffe": 2.0},
  {"kategorie": "Gemüse", "name": "Knoblauch frisch", "pro": 100, "eiweiss": 6.1, "fett": 0.1, "kh": 28.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Karotten roh", "pro": 100, "eiweiss": 1.1, "fett": 0.2, "kh": 4.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Karotten gekocht", "pro": 100, "eiweiss": 0.8, "fett": 0.2, "kh": 3.1, "cholesterin": 0.0, "natrium": 42.0, "ballaststoffe": 2.5},
  {"kategorie": "Gemüse", "name": "Babykarotten IGLO", "pro": 100, "eiweiss": 0.7, "fett": 0.0, "kh": 4.5, "cholesterin": 0.0, "natrium": 60.0, "ballaststoffe": 3.4},
  {"kategorie": "Gemüse", "name": "Kürbis roh", "pro": 100, "eiweiss": 1.0, "fett": 0.1, "kh": 5.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Paprika roh", "pro": 100, "eiweiss": 1.2, "fett": 0.3, "kh": 2.9, "cholesterin": 0.0, "natrium": 2.0, "ballaststoffe": 3.6},
  {"kategorie": "Gemüse", "name": "Radieschen, roh", "pro": 100, "eiweiss": 1.1, "fett": 0.1, "kh": 2.0, "cholesterin": 0.0, "natrium": 17.0, "ballaststoffe": 1.6},
  {"kategorie": "Gemüse", "name": "Rettich, roh", "pro": 100, "eiweiss": 1.0, "fett": 0.2, "kh": 1.9, "cholesterin": 0.0, "natrium": 18.0, "ballaststoffe": 2.5},
  {"kategorie": "Gemüse", "name": "Kohlsprossen gekocht", "pro": 100, "eiweiss": 3.8, "fett": 0.5, "kh": 2.4, "cholesterin": 0.0, "natrium": 5.0, "ballaststoffe": 4.0},
  {"kategorie": "Gemüse", "name": "Rote Rüben gekocht", "pro": 100, "eiweiss": 1.1, "fett": 0.1, "kh": 5.0, "cholesterin": 0.0, "natrium": 48.0, "ballaststoffe": 2.0},
  {"kategorie": "Gemüse", "name": "Rotkraut roh", "pro": 100, "eiweiss": 1.5, "fett": 0.2, "kh": 3.2, "cholesterin": 0.0, "natrium": 4.0, "ballaststoffe": 2.5},
  {"kategorie": "Gemüse", "name": "Sauerkraut, abgetropft roh", "pro": 100, "eiweiss": 1.5, "fett": 0.3, "kh": 0.8, "cholesterin": 0.0, "natrium": 355.0, "ballaststoffe": 2.2},
  {"kategorie": "Gemüse", "name": "Salz-Dill-Gurken", "pro": 100, "eiweiss": 1.0, "fett": 0.2, "kh": 3.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Schwarzwurzeln roh", "pro": 100, "eiweiss": 1.4, "fett": 0.4, "kh": 1.6, "cholesterin": 0.0, "natrium": 5.0, "ballaststoffe": 17.0},
  {"kategorie": "Gemüse", "name": "Spargel, gekocht", "pro": 100, "eiweiss": 1.7, "fett": 0.1, "kh": 1.2, "cholesterin": 0.0, "natrium": 2000.0, "ballaststoffe": 1.0},
  {"kategorie": "Gemüse", "name": "Spinat, gekocht", "pro": 100, "eiweiss": 2.3, "fett": 0.3, "kh": 0.5, "cholesterin": 0.0, "natrium": 46.0, "ballaststoffe": 2.1},
  {"kategorie": "Gemüse", "name": "Knollensellerie roh", "pro": 100, "eiweiss": 1.6, "fett": 0.3, "kh": 2.3, "cholesterin": 0.0, "natrium": 132.0, "ballaststoffe": 2.6},
  {"kategorie": "Gemüse", "name": "Tomaten (Dose)", "pro": 100, "eiweiss": 1.1, "fett": 0.2, "kh": 3.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Tomaten, roh", "pro": 100, "eiweiss": 1.0, "fett": 0.2, "kh": 2.6, "cholesterin": 0.0, "natrium": 3.0, "ballaststoffe": 1.0},
  {"kategorie": "Gemüse", "name": "Gurke roh", "pro": 100, "eiweiss": 0.6, "fett": 0.2, "kh": 1.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Staudensellerie roh", "pro": 100, "eiweiss": 1.2, "fett": 0.2, "kh": 2.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Weißkraut roh", "pro": 100, "eiweiss": 1.3, "fett": 0.2, "kh": 4.2, "cholesterin": 0.0, "natrium": 13.0, "ballaststoffe": 3.0},
  {"kategorie": "Gemüse", "name": "Zucchini roh", "pro": 100, "eiweiss": 1.6, "fett": 0.4, "kh": 2.2, "cholesterin": 0.0, "natrium": 3.0, "ballaststoffe": 1.1},
  {"kategorie": "Gemüse", "name": "Zucchini gegart", "pro": 100, "eiweiss": 2.1, "fett": 0.3, "kh": 2.4, "cholesterin": 0.0, "natrium": 3.0, "ballaststoffe": 1.1},
  {"kategorie": "Gemüse", "name": "Zwiebel, roh", "pro": 100, "eiweiss": 1.3, "fett": 0.3, "kh": 4.9, "cholesterin": 0.0, "natrium": 9.0, "ballaststoffe": 1.8},
  {"kategorie": "Gemüse", "name": "Oliven, grün mariniert", "pro": 100, "eiweiss": 1.4, "fett": 13.3, "kh": 1.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Gemüse", "name": "Oliven, schwarz \"griech. Art\"", "pro": 100, "eiweiss": 2.2, "fett": 35.8, "kh": 4.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Pilze", "name": "Austernpilze", "pro": 100, "eiweiss": 2.4, "fett": 0.1, "kh": 0.0, "cholesterin": 0.0, "natrium": 6.0, "ballaststoffe": 5.9},
  {"kategorie": "Pilze", "name": "Champignon in der Dose", "pro": 100, "eiweiss": 2.3, "fett": 0.5, "kh": 0.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Pilze", "name": "Champignon (Zucht-)", "pro": 100, "eiweiss": 2.7, "fett": 0.2, "kh": 0.6, "cholesterin": 0.0, "natrium": 8.0, "ballaststoffe": 2.0},
  {"kategorie": "Pilze", "name": "Steinpilz roh", "pro": 100, "eiweiss": 2.8, "fett": 0.4, "kh": 0.5, "cholesterin": 0.0, "natrium": 6.0, "ballaststoffe": 6.0},
  {"kategorie": "Öle", "name": "Rapsöl", "pro": 100, "eiweiss": 0.0, "fett": 99.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Öle", "name": "MCT-Öl C8+C10", "pro": 100, "eiweiss": 0.0, "fett": 100.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Öle", "name": "Maiskeimöl", "pro": 100, "eiweiss": 0.0, "fett": 99.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 1.0, "ballaststoffe": 0.0},
  {"kategorie": "Öle", "name": "Vita Pflanzenmargarine*", "pro": 100, "eiweiss": 0.2, "fett": 80.0, "kh": 0.3, "cholesterin": 0.2, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Öle", "name": "Becel Diät-Speiseöl", "pro": 100, "eiweiss": 0.0, "fett": 100.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Öle", "name": "Olivenöl", "pro": 100, "eiweiss": 0.0, "fett": 99.6, "kh": 0.2, "cholesterin": 1.0, "natrium": 1.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Thomy \"Sauce Béarnaise\"*", "pro": 100, "eiweiss": 1.3, "fett": 19.1, "kh": 6.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Kuner Sauce Tartare", "pro": 100, "eiweiss": 1.0, "fett": 43.0, "kh": 8.0, "cholesterin": 61.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Majonnaise 80% Fett KUNER", "pro": 100, "eiweiss": 2.0, "fett": 80.0, "kh": 1.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Butter", "pro": 100, "eiweiss": 0.7, "fett": 82.0, "kh": 0.6, "cholesterin": 240.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Schlagobers NÖM", "pro": 100, "eiweiss": 2.3, "fett": 36.0, "kh": 3.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Saurer Rahm 15 % NÖM", "pro": 100, "eiweiss": 3.0, "fett": 15.0, "kh": 3.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Creme Fraîche NÖM", "pro": 100, "eiweiss": 2.3, "fett": 36.0, "kh": 2.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Topfen 20 % NÖM", "pro": 100, "eiweiss": 10.8, "fett": 4.4, "kh": 3.6, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Topfen 40 % NÖM", "pro": 100, "eiweiss": 9.0, "fett": 10.3, "kh": 3.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Mascarpone Kärntnermilch", "pro": 100, "eiweiss": 3.8, "fett": 41.0, "kh": 2.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Gervais 65 % Schärdinger", "pro": 100, "eiweiss": 9.5, "fett": 25.5, "kh": 2.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Picotta 20 % Desserta", "pro": 100, "eiweiss": 12.5, "fett": 4.5, "kh": 3.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Emmentaler 45% F.i.T.", "pro": 100, "eiweiss": 28.9, "fett": 30.0, "kh": 0.0, "cholesterin": 84.0, "natrium": 400.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Schafkäse 45 % F. i.T.", "pro": 100, "eiweiss": 17.0, "fett": 18.0, "kh": 0.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Landfrischkäse 10 %", "pro": 100, "eiweiss": 12.7, "fett": 2.2, "kh": 3.1, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Philadelphia KRAFT", "pro": 100, "eiweiss": 6.0, "fett": 29.5, "kh": 2.6, "cholesterin": 100.0, "natrium": 520.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Appenzeller, 50% Fett i.Tr.", "pro": 100, "eiweiss": 25.4, "fett": 31.6, "kh": 0.0, "cholesterin": 74.0, "natrium": 600.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Bavaria Blue", "pro": 100, "eiweiss": 13.2, "fett": 40.0, "kh": 0.0, "cholesterin": 112.0, "natrium": 700.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Bel Paese", "pro": 100, "eiweiss": 25.4, "fett": 30.2, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Butterkäse 60% Fett i.Tr.", "pro": 100, "eiweiss": 17.0, "fett": 34.7, "kh": 0.0, "cholesterin": 81.0, "natrium": 700.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Camembert 55 % FIT Schärdinger", "pro": 100, "eiweiss": 19.5, "fett": 29.4, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Cambozola, 70% Fetti.Tr.", "pro": 100, "eiweiss": 13.2, "fett": 40.0, "kh": 0.0, "cholesterin": 112.0, "natrium": 700.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Mozarella", "pro": 100, "eiweiss": 18.6, "fett": 19.8, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Schmelzkäse 45% Fett i. Tr.", "pro": 100, "eiweiss": 14.4, "fett": 22.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Käse", "name": "Gouda 45% Fett i. Tr.", "pro": 100, "eiweiss": 24.0, "fett": 25.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Eier", "name": "Ei ganz versprudelt", "pro": 100, "eiweiss": 12.9, "fett": 11.7, "kh": 0.6, "cholesterin": 604.0, "natrium": 144.0, "ballaststoffe": 0.0},
  {"kategorie": "Eier", "name": "Eidotter", "pro": 100, "eiweiss": 16.1, "fett": 31.9, "kh": 0.3, "cholesterin": 1650.0, "natrium": 50.0, "ballaststoffe": 0.0},
  {"kategorie": "Eier", "name": "Eiklar", "pro": 100, "eiweiss": 10.9, "fett": 0.2, "kh": 0.7, "cholesterin": 0.0, "natrium": 170.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Trockenmilchpulver aus Vollmilch", "pro": 100, "eiweiss": 25.5, "fett": 27.0, "kh": 37.1, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Trockenmilchpulver aus Magermilch", "pro": 100, "eiweiss": 35.3, "fett": 1.0, "kh": 49.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Extra Vollmilch 4,5 % Fett", "pro": 100, "eiweiss": 3.3, "fett": 4.5, "kh": 4.7, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Milchprodukte", "name": "Vollmilch 3,6 % NÖM", "pro": 100, "eiweiss": 3.3, "fett": 3.6, "kh": 4.7, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Würstchen Frankfurter Art Meica", "pro": 100, "eiweiss": 11.0, "fett": 23.0, "kh": 0.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Wiener Würstchen Meica", "pro": 100, "eiweiss": 12.0, "fett": 21.0, "kh": 0.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Frankfurter JANatürlich", "pro": 100, "eiweiss": 12.6, "fett": 19.9, "kh": 0.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Putenfrankfurter Stastnik", "pro": 100, "eiweiss": 13.0, "fett": 15.0, "kh": 1.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Blutwurst", "pro": 100, "eiweiss": 10.0, "fett": 29.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Cabanossi (clever)", "pro": 100, "eiweiss": 27.0, "fett": 45.0, "kh": 1.1, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Leberkäse", "pro": 100, "eiweiss": 12.4, "fett": 27.5, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Leberwurst grob", "pro": 100, "eiweiss": 15.9, "fett": 29.2, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Salami", "pro": 100, "eiweiss": 18.5, "fett": 33.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Schinken ohne Fettrand (z.B. Toastschinken)", "pro": 100, "eiweiss": 29.7, "fett": 2.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Schinken, gekocht (Teilsames)", "pro": 100, "eiweiss": 19.5, "fett": 12.8, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Wurst", "name": "Frühstücksspeck durchwachsen", "pro": 100, "eiweiss": 9.1, "fett": 65.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Schwein Bauch", "pro": 100, "eiweiss": 17.8, "fett": 21.1, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Putenbrust ohne Haut", "pro": 100, "eiweiss": 24.1, "fett": 1.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Rinderfaschiertes", "pro": 100, "eiweiss": 20.0, "fett": 15.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Hühnerbrust ohne Haut", "pro": 100, "eiweiss": 22.8, "fett": 0.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Kalbsschnitzelfleisch", "pro": 100, "eiweiss": 20.6, "fett": 1.4, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Lammfleisch - Keule", "pro": 100, "eiweiss": 18.0, "fett": 18.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fleisch", "name": "Rindfleisch - Hochrippe, Rostbraten, Rippe", "pro": 100, "eiweiss": 20.2, "fett": 8.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Ananas roh", "pro": 100, "eiweiss": 0.4, "fett": 0.2, "kh": 12.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Apfel geschält roh", "pro": 100, "eiweiss": 0.3, "fett": 0.4, "kh": 12.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Apfel ungeschält roh", "pro": 100, "eiweiss": 0.3, "fett": 0.6, "kh": 11.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Banane roh", "pro": 100, "eiweiss": 1.0, "fett": 0.2, "kh": 20.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Papaya roh", "pro": 100, "eiweiss": 0.6, "fett": 0.1, "kh": 2.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Rhabarber, gekocht ohne Zutaten", "pro": 100, "eiweiss": 0.5, "fett": 0.1, "kh": 1.0, "cholesterin": 0.0, "natrium": 1.0, "ballaststoffe": 2.0},
  {"kategorie": "Obst", "name": "Schwarze Ribisel", "pro": 100, "eiweiss": 1.3, "fett": 0.2, "kh": 6.1, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Erdbeeren TK", "pro": 100, "eiweiss": 0.8, "fett": 0.4, "kh": 6.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Erdbeeren frisch", "pro": 100, "eiweiss": 0.8, "fett": 0.4, "kh": 5.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Himbeeren TK oder Frisch", "pro": 100, "eiweiss": 1.3, "fett": 0.3, "kh": 4.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Ribiseln TK oder Frisch", "pro": 100, "eiweiss": 1.1, "fett": 0.2, "kh": 4.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Brombeeren TK oder Frisch", "pro": 100, "eiweiss": 1.2, "fett": 1.0, "kh": 6.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Holunderbeeren TK oder Frisch", "pro": 100, "eiweiss": 2.6, "fett": 1.7, "kh": 6.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Orange ohne Schale", "pro": 100, "eiweiss": 1.0, "fett": 0.2, "kh": 8.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Orangensaft ohne Zuckerzusatz", "pro": 100, "eiweiss": 0.7, "fett": 0.2, "kh": 9.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Zitronensaft", "pro": 100, "eiweiss": 0.4, "fett": 0.1, "kh": 2.4, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Apfelsaft ohne Zuckerzusatz 100%", "pro": 100, "eiweiss": 0.1, "fett": 0.0, "kh": 11.7, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Apfelmus ohne Zuckerzusatz", "pro": 100, "eiweiss": 0.2, "fett": 0.1, "kh": 19.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Tomatenmark ohne Zuckerzusatz", "pro": 100, "eiweiss": 2.3, "fett": 0.5, "kh": 5.5, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Tomatenmark IGLO TK", "pro": 100, "eiweiss": 2.0, "fett": 0.3, "kh": 7.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fisch", "name": "Forelle TK oder Frisch", "pro": 100, "eiweiss": 19.5, "fett": 2.7, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fisch", "name": "Heilbuttfilet TK oder Frisch", "pro": 100, "eiweiss": 20.1, "fett": 2.3, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fisch", "name": "Thunfisch in der Dose in Öl (ganzer Inhalt)", "pro": 100, "eiweiss": 23.8, "fett": 20.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fisch", "name": "Markrelle geräuchert", "pro": 100, "eiweiss": 20.7, "fett": 15.5, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fisch", "name": "Karpfen", "pro": 100, "eiweiss": 18.0, "fett": 4.8, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Fisch", "name": "Scholle TK oder Frisch", "pro": 100, "eiweiss": 17.1, "fett": 1.9, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Nüsse", "name": "Mandeln gemahlen", "pro": 100, "eiweiss": 24.0, "fett": 53.0, "kh": 4.7, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonstiges", "name": "Kakaopulver entölt", "pro": 100, "eiweiss": 20.0, "fett": 24.0, "kh": 11.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonstiges", "name": "Kokosmilch", "pro": 100, "eiweiss": 0.25, "fett": 0.4, "kh": 4.9, "cholesterin": 0.0, "natrium": 63.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Benefiber (Lösliche Ballaststoffe)", "pro": 100, "eiweiss": 0.0, "fett": 0.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 20.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Guarkernmehl (Bindefix)", "pro": 100, "eiweiss": 4.5, "fett": 0.5, "kh": 1.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Protifar plus (Eiweißkonzentrat)", "pro": 100, "eiweiss": 88.5, "fett": 2.0, "kh": 1.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Johannisbrotkernmehl", "pro": 100, "eiweiss": 4.5, "fett": 1.4, "kh": 7.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Getreide", "name": "Wasa köstlich mit 24% Ballaststoffen", "pro": 100, "eiweiss": 13.0, "fett": 8.0, "kh": 45.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Grießbrei Ja Natürlich milchfrei, zuckerfrei", "pro": 100, "eiweiss": 11.9, "fett": 2.5, "kh": 67.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Getreide", "name": "Leicht & Cross Knusperbrot", "pro": 100, "eiweiss": 13.0, "fett": 3.5, "kh": 72.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "HIPP Reis mit Karotten und Pute", "pro": 100, "eiweiss": 2.4, "fett": 3.1, "kh": 8.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "HIPP Kartoffel-Gemüse mit Bio-Rindfleisch", "pro": 100, "eiweiss": 2.3, "fett": 2.9, "kh": 7.6, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "HiPP Bio-Hühnchenfleisch Zubereitung", "pro": 100, "eiweiss": 7.8, "fett": 5.8, "kh": 6.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "HIPP Karotten-Kartoffelgemüse mit Bio-Lamm", "pro": 100, "eiweiss": 2.6, "fett": 1.9, "kh": 10.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "HIPP Äpfel mit Bananen", "pro": 100, "eiweiss": 0.5, "fett": 0.1, "kh": 13.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "HIPP Milchbrei Grieß-Banane", "pro": 100, "eiweiss": 13.8, "fett": 11.8, "kh": 63.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Maltodextrin 6", "pro": 100, "eiweiss": 0.0, "fett": 0.0, "kh": 96.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Kohlenhydratfrei SHS", "pro": 100, "eiweiss": 28.9, "fett": 60.6, "kh": 0.1, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Getreide", "name": "Hartweizengrießteigwaren gekocht gewogen", "pro": 100, "eiweiss": 5.38, "fett": 0.51, "kh": 30.32, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Getreide", "name": "Haferflocken", "pro": 100, "eiweiss": 14.0, "fett": 7.0, "kh": 59.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Himmeltau Grießbrei", "pro": 100, "eiweiss": 10.0, "fett": 0.9, "kh": 68.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Aptamil 1", "pro": 100, "eiweiss": 9.7, "fett": 24.7, "kh": 53.8, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Aptamil Pre (Pulver)", "pro": 100, "eiweiss": 9.5, "fett": 24.8, "kh": 53.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Ketocal 4:1", "pro": 100, "eiweiss": 14.4, "fett": 69.2, "kh": 2.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Ketocal 3:1", "pro": 100, "eiweiss": 15.4, "fett": 68.6, "kh": 7.2, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Ketocal 4:1 (Vanille)", "pro": 100, "eiweiss": 14.4, "fett": 69.2, "kh": 2.9, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Aptamil Profutura 1 (trinkfertig)", "pro": 100, "eiweiss": 1.3, "fett": 3.4, "kh": 7.3, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Aptamil Profutura 1", "pro": 100, "eiweiss": 9.7, "fett": 25.0, "kh": 53.7, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "Liquigen", "pro": 100, "eiweiss": 0.0, "fett": 50.4, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonde / Spezial", "name": "MCT Nutricia (100%)", "pro": 100, "eiweiss": 0.0, "fett": 95.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Sonstiges", "name": "Wasser", "pro": 100, "eiweiss": 0.0, "fett": 0.0, "kh": 0.0, "cholesterin": 0.0, "natrium": 0.0, "ballaststoffe": 0.0},
  {"kategorie": "Obst", "name": "Heidelbeeren", "pro": 100, "eiweiss": 0.6, "fett": 0.3, "kh": 12, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Obst", "name": "Marille", "pro": 100, "eiweiss": 0.9, "fett": 0.1, "kh": 8.54, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Rotbarsch, gegart", "pro": 100, "eiweiss": 21.53, "fett": 4.3, "kh": 0, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Fleisch", "name": "Schweinefilet", "pro": 100, "eiweiss": 22, "fett": 2, "kh": 0, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Fisch", "name": "Thunfisch in Öl (Dose, abgetropft)", "pro": 100, "eiweiss": 25, "fett": 9, "kh": 0, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
  {"kategorie": "Öle", "name": "Streichgenuss (Schärdinger)", "pro": 100, "eiweiss": 0.5, "fett": 75, "kh": 0.6, "cholesterin": 0, "natrium": 0, "ballaststoffe": 0},
];
