// Standard-Rezepte für die ketogene Sondennahrung (40 Stück: 20 mit / 20 ohne KetoCal).
// Ausgewogen über Fleisch, Fisch, vegetarisch und Obst; alle erreichen 1,8:1 sicher.
// Österreichische Zutatennamen. Felder: name, icon, ketocal, zubereitung, thermomix, items.
const RECIPES_SONDE = [
  {
    name: "Hendl-Zucchini-Creme",
    icon: "🍗",
    ketocal: false,
    zubereitung: "Zucchini weich garen, mit dem gegarten Hendl und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern. Wasser und Hendl zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 25 }, { food: "Zucchini gegart", grams: 70 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Hendl-Karotten-Creme",
    icon: "🍗",
    ketocal: false,
    zubereitung: "Karotten weich garen, mit dem gegarten Hendl und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Hendl zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 25 }, { food: "Karotten gekocht", grams: 50 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Pute-Erdäpfel-Püree",
    icon: "🦃",
    ketocal: false,
    zubereitung: "Erdäpfel weich garen, mit dem gegarten Pute und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern. Wasser und Pute zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Putenbrust ohne Haut", grams: 25 }, { food: "Kartoffel gekocht", grams: 40 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Rindfleisch-Karotten-Püree",
    icon: "🥩",
    ketocal: false,
    zubereitung: "Karotten weich garen, mit dem gegarten Rindfleisch und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Rindfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Rindfleisch (mager)", grams: 25 }, { food: "Karotten gekocht", grams: 50 }, { food: "Rapsöl", grams: 10 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Schweinefilet-Karfiol-Creme",
    icon: "🥩",
    ketocal: false,
    zubereitung: "Karfiol weich garen, mit dem gegarten Schweinefilet und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern. Wasser und Schweinefilet zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Schweinefilet", grams: 25 }, { food: "Karfiol gekocht", grams: 60 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Hendl-Karfiol-Creme",
    icon: "🍗",
    ketocal: false,
    zubereitung: "Karfiol weich garen, mit dem gegarten Hendl und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern. Wasser und Hendl zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 25 }, { food: "Karfiol gekocht", grams: 60 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Forelle-Erdäpfel-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Erdäpfel weich garen, mit dem gegarten Forelle und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern. Wasser und Forelle zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Forelle TK oder Frisch", grams: 30 }, { food: "Kartoffel gekocht", grams: 30 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Heilbutt-Brokkoli-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Brokkoli weich garen, mit dem gegarten Heilbutt und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Brokkoli 5 Sek./Stufe 5 zerkleinern. Wasser und Heilbutt zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Heilbuttfilet TK oder Frisch", grams: 30 }, { food: "Broccoli, gekocht", grams: 50 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Scholle-Karotten-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Karotten weich garen, mit dem gegarten Scholle und Wasser fein pürieren, dann Rapsöl untermischen.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Scholle zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Scholle TK oder Frisch", grams: 30 }, { food: "Karotten gekocht", grams: 50 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Thunfisch-Zucchini-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Zucchini weich garen, mit dem gegarten Thunfisch und Wasser fein pürieren, dann Olivenöl untermischen.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern. Wasser und Thunfisch zugeben, 12 Min./100 °C/Stufe 1 garen. Olivenöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Thunfisch in Öl (Dose, abgetropft)", grams: 30 }, { food: "Zucchini gegart", grams: 70 }, { food: "Olivenöl", grams: 12 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Ei-Zucchini-Creme",
    icon: "🥚",
    ketocal: false,
    zubereitung: "Ei hart kochen, mit gegartem Zucchini, Wasser und Rapsöl fein pürieren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Geschältes hart gekochtes Ei und Rapsöl zugeben und 30 Sek./Stufe 7 cremig pürieren.",
    items: [ { food: "Ei ganz versprudelt", grams: 40 }, { food: "Zucchini gegart", grams: 60 }, { food: "Rapsöl", grams: 8 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Ei-Erdäpfel-Creme",
    icon: "🥚",
    ketocal: false,
    zubereitung: "Ei hart kochen, mit gegartem Erdäpfel, Wasser und Butter fein pürieren.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Geschältes hart gekochtes Ei und Butter zugeben und 30 Sek./Stufe 7 cremig pürieren.",
    items: [ { food: "Ei ganz versprudelt", grams: 40 }, { food: "Kartoffel gekocht", grams: 30 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Spinat-Ei-Creme",
    icon: "🥬",
    ketocal: false,
    zubereitung: "Ei hart kochen, mit gegartem Spinat, Wasser und Rapsöl fein pürieren.",
    thermomix: "Spinat 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Geschältes hart gekochtes Ei und Rapsöl zugeben und 30 Sek./Stufe 7 cremig pürieren.",
    items: [ { food: "Ei ganz versprudelt", grams: 40 }, { food: "Spinat, gekocht", grams: 50 }, { food: "Rapsöl", grams: 8 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Brokkoli-Ei-Creme",
    icon: "🥦",
    ketocal: false,
    zubereitung: "Ei hart kochen, mit gegartem Brokkoli, Wasser und Rapsöl fein pürieren.",
    thermomix: "Brokkoli 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Geschältes hart gekochtes Ei und Rapsöl zugeben und 30 Sek./Stufe 7 cremig pürieren.",
    items: [ { food: "Ei ganz versprudelt", grams: 40 }, { food: "Broccoli, gekocht", grams: 60 }, { food: "Rapsöl", grams: 8 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Erdäpfel-Gemüse-Creme",
    icon: "🥔",
    ketocal: false,
    zubereitung: "Erdäpfel weich garen, mit Wasser fein pürieren und Rapsöl untermischen.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Kartoffel gekocht", grams: 30 }, { food: "Zucchini gegart", grams: 50 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Karfiol-Erdäpfel-Püree",
    icon: "🥦",
    ketocal: false,
    zubereitung: "Karfiol weich garen, mit Wasser fein pürieren und Rapsöl untermischen.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Karfiol gekocht", grams: 60 }, { food: "Kartoffel gekocht", grams: 30 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Bananen-Brei",
    icon: "🍌",
    ketocal: false,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann Butter und Banane zugeben und fein pürieren.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann Butter und Banane zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Banane roh", grams: 30 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Butter", grams: 10 }, { food: "Wasser", grams: 80 } ],
  },
  {
    name: "Apfelmus-Brei",
    icon: "🍎",
    ketocal: false,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann Butter und Apfelmus zugeben und fein pürieren.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann Butter und Apfelmus zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Apfelmus ohne Zuckerzusatz", grams: 40 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Butter", grams: 10 }, { food: "Wasser", grams: 80 } ],
  },
  {
    name: "Marillen-Brei",
    icon: "🍑",
    ketocal: false,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann Butter und Marillen zugeben und fein pürieren.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann Butter und Marillen zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Marille", grams: 50 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Butter", grams: 10 }, { food: "Wasser", grams: 70 } ],
  },
  {
    name: "Beeren-Brei",
    icon: "🫐",
    ketocal: false,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann Butter und Heidelbeeren zugeben und fein pürieren.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann Butter und Heidelbeeren zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Heidelbeeren", grams: 50 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Butter", grams: 10 }, { food: "Wasser", grams: 70 } ],
  },
  {
    name: "Hendl-Karotten-Brei (KetoCal)",
    icon: "🍗",
    ketocal: true,
    zubereitung: "Karotten weich garen, mit dem gegarten Hendl und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Hendl zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Karotten gekocht", grams: 40 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Hendl-Zucchini-Brei (KetoCal)",
    icon: "🍗",
    ketocal: true,
    zubereitung: "Zucchini weich garen, mit dem gegarten Hendl und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern. Wasser und Hendl zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Zucchini gegart", grams: 60 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Pute-Erdäpfel-Brei (KetoCal)",
    icon: "🦃",
    ketocal: true,
    zubereitung: "Erdäpfel weich garen, mit dem gegarten Pute und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern. Wasser und Pute zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Putenbrust ohne Haut", grams: 20 }, { food: "Kartoffel gekocht", grams: 30 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Rindfleisch-Karotten-Brei (KetoCal)",
    icon: "🥩",
    ketocal: true,
    zubereitung: "Karotten weich garen, mit dem gegarten Rindfleisch und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Rindfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Rindfleisch (mager)", grams: 20 }, { food: "Karotten gekocht", grams: 40 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 5 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Schweinefilet-Gemüse-Brei (KetoCal)",
    icon: "🥩",
    ketocal: true,
    zubereitung: "Karfiol weich garen, mit dem gegarten Schweinefilet und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern. Wasser und Schweinefilet zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Schweinefilet", grams: 20 }, { food: "Karfiol gekocht", grams: 50 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Hendl-Karfiol-Brei (KetoCal)",
    icon: "🍗",
    ketocal: true,
    zubereitung: "Karfiol weich garen, mit dem gegarten Hendl und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern. Wasser und Hendl zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Karfiol gekocht", grams: 50 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Forelle-Erdäpfel-Brei (KetoCal)",
    icon: "🐟",
    ketocal: true,
    zubereitung: "Erdäpfel weich garen, mit dem gegarten Forelle und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern. Wasser und Forelle zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Forelle TK oder Frisch", grams: 25 }, { food: "Kartoffel gekocht", grams: 30 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Heilbutt-Brokkoli-Brei (KetoCal)",
    icon: "🐟",
    ketocal: true,
    zubereitung: "Brokkoli weich garen, mit dem gegarten Heilbutt und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Brokkoli 5 Sek./Stufe 5 zerkleinern. Wasser und Heilbutt zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Heilbuttfilet TK oder Frisch", grams: 25 }, { food: "Broccoli, gekocht", grams: 50 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 55 } ],
  },
  {
    name: "Scholle-Karotten-Brei (KetoCal)",
    icon: "🐟",
    ketocal: true,
    zubereitung: "Karotten weich garen, mit dem gegarten Scholle und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Scholle zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Scholle TK oder Frisch", grams: 25 }, { food: "Karotten gekocht", grams: 50 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 55 } ],
  },
  {
    name: "Rotbarsch-Gemüse-Brei (KetoCal)",
    icon: "🐟",
    ketocal: true,
    zubereitung: "Zucchini weich garen, mit dem gegarten Rotbarsch und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern. Wasser und Rotbarsch zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Rotbarsch, gegart", grams: 25 }, { food: "Zucchini gegart", grams: 60 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Gemüse-Erdäpfelbrei (Variante 1)",
    icon: "🥔",
    ketocal: true,
    zubereitung: "Erdäpfel weich garen, mit Wasser und KetoCal 3:1 fein pürieren und Rapsöl untermischen.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./90 °C/Stufe 1 garen. KetoCal 3:1 und Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Kartoffel gekocht", grams: 30 }, { food: "Zucchini gegart", grams: 50 }, { food: "Ketocal 3:1", grams: 12 }, { food: "Rapsöl", grams: 9 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Gemüse-Erdäpfelbrei (Variante 2)",
    icon: "🥔",
    ketocal: true,
    zubereitung: "Erdäpfel weich garen, mit Wasser und KetoCal 3:1 fein pürieren und Rapsöl untermischen.",
    thermomix: "Erdäpfel 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./90 °C/Stufe 1 garen. KetoCal 3:1 und Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Kartoffel gekocht", grams: 30 }, { food: "Zucchini gegart", grams: 50 }, { food: "Ketocal 3:1", grams: 12 }, { food: "Rapsöl", grams: 7 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Karfiol-Erdäpfel-Brei (KetoCal)",
    icon: "🥦",
    ketocal: true,
    zubereitung: "Karfiol weich garen, mit Wasser und KetoCal 3:1 fein pürieren und Rapsöl untermischen.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./90 °C/Stufe 1 garen. KetoCal 3:1 und Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Karfiol gekocht", grams: 50 }, { food: "Kartoffel gekocht", grams: 30 }, { food: "Ketocal 3:1", grams: 12 }, { food: "Rapsöl", grams: 8 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Zucchini-Brei (KetoCal)",
    icon: "🥒",
    ketocal: true,
    zubereitung: "Zucchini weich garen, mit Wasser und KetoCal 3:1 fein pürieren und Rapsöl untermischen.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./90 °C/Stufe 1 garen. KetoCal 3:1 und Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Zucchini gegart", grams: 80 }, { food: "Ketocal 3:1", grams: 12 }, { food: "Rapsöl", grams: 9 }, { food: "Wasser", grams: 40 } ],
  },
  {
    name: "Karottensuppe",
    icon: "🥕",
    ketocal: true,
    zubereitung: "Karotten weich garen, mit Wasser und KetoCal 3:1 fein pürieren und Butter untermischen.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./90 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Karotten roh", grams: 120 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Schlagobers NÖM", grams: 20 }, { food: "Butter", grams: 6 }, { food: "Wasser", grams: 110 } ],
  },
  {
    name: "Ei-Gemüse-Brei (KetoCal)",
    icon: "🥚",
    ketocal: true,
    zubereitung: "Zucchini weich garen, mit dem gegarten Hühnerei, Vollei, frisch und Wasser fein pürieren. KetoCal 3:1 und Butter unterrühren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerei, Vollei, frisch zugeben, 12 Min./100 °C/Stufe 1 garen. KetoCal 3:1 und Butter zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Ei ganz versprudelt", grams: 30 }, { food: "Zucchini gegart", grams: 50 }, { food: "Ketocal 3:1", grams: 10 }, { food: "Butter", grams: 5 }, { food: "Wasser", grams: 50 } ],
  },
  {
    name: "Obstbrei – Banane",
    icon: "🍌",
    ketocal: true,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann KetoCal 3:1 einrühren und Butter sowie Banane zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann KetoCal 3:1, Butter und Banane zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Wasser", grams: 100 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Ketocal 3:1", grams: 15 }, { food: "Butter", grams: 4 }, { food: "Banane roh", grams: 20 } ],
  },
  {
    name: "Obstbrei – Apfelmus",
    icon: "🍎",
    ketocal: true,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann KetoCal 3:1 einrühren und Butter sowie Apfelmus zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann KetoCal 3:1, Butter und Apfelmus zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Wasser", grams: 100 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Ketocal 3:1", grams: 15 }, { food: "Butter", grams: 3 }, { food: "Apfelmus ohne Zuckerzusatz", grams: 20 } ],
  },
  {
    name: "Obstbrei – Marille",
    icon: "🍑",
    ketocal: true,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann KetoCal 3:1 einrühren und Butter sowie Marillen zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann KetoCal 3:1, Butter und Marillen zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [ { food: "Wasser", grams: 100 }, { food: "Johannisbrotkernmehl", grams: 2 }, { food: "Ketocal 3:1", grams: 15 }, { food: "Butter", grams: 4 }, { food: "Marille", grams: 30 } ],
  },
  {
    name: "Milch-Grieß-Obstbrei",
    icon: "🥣",
    ketocal: true,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl andicken, auf 45–50 °C abkühlen lassen, Grießbrei und KetoCal 3:1 einrühren, dann Butter und Apfelmus zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Abkühlen lassen, dann Grießbrei, KetoCal 3:1, Butter und Apfelmus zugeben und 20 Sek./Stufe 6 rühren.",
    items: [ { food: "Wasser", grams: 120 }, { food: "Apfelmus ohne Zuckerzusatz", grams: 15 }, { food: "Himmeltau Grießbrei", grams: 5 }, { food: "Ketocal 3:1", grams: 12 }, { food: "Butter", grams: 11 }, { food: "Johannisbrotkernmehl", grams: 2 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Brokkoli",
    icon: "🥦",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Brokkoli 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Broccoli, gekocht", grams: 45 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Erbsen",
    icon: "🫛",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Erbsen 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Erbsen grün, roh und TK", grams: 30 }, { food: "Rapsöl", grams: 16 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Karfiol",
    icon: "🥬",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Karfiol gekocht", grams: 45 }, { food: "Rapsöl", grams: 11 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Karotte & Rind",
    icon: "🥩",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Rindfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Rindfleisch (mager)", grams: 30 }, { food: "Karotten roh", grams: 45 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Karotte",
    icon: "🥕",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Karotten roh", grams: 45 }, { food: "Rapsöl", grams: 12 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Kürbis",
    icon: "🎃",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Kürbis 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Kürbis roh", grams: 45 }, { food: "Rapsöl", grams: 13 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Rote Rüben",
    icon: "🟣",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Rote Rüben 5 Sek./Stufe 5 zerkleinern. Wasser und Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Hühnerbrust ohne Haut", grams: 20 }, { food: "Rote Rüben gekocht", grams: 45 }, { food: "Rapsöl", grams: 13 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Gemüse-Fleischbrei – Rote Rüben & Rind",
    icon: "🥩",
    ketocal: false,
    zubereitung: "Das Gemüse weich garen, mit dem gegarten Fleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Rote Rüben 5 Sek./Stufe 5 zerkleinern. Wasser und Rindfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Rindfleisch (mager)", grams: 30 }, { food: "Rote Rüben gekocht", grams: 30 }, { food: "Rapsöl", grams: 16 }, { food: "Wasser", grams: 60 } ],
  },
  {
    name: "Erdäpfel-Spinat-Creme",
    icon: "🥬",
    ketocal: false,
    zubereitung: "Erdäpfel und Gemüse weich garen, mit Wasser fein pürieren und das Rapsöl untermischen.",
    thermomix: "Erdäpfel und Gemüse 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Kartoffel gekocht", grams: 23 }, { food: "Spinat, gekocht", grams: 30 }, { food: "Rapsöl", grams: 8 }, { food: "Wasser", grams: 80 } ],
  },
  {
    name: "Rind-Spinat-Brei",
    icon: "🥩",
    ketocal: false,
    zubereitung: "Spinat und Erdäpfel weich garen, mit dem gegarten Rindfleisch und Wasser fein pürieren, anschließend das Rapsöl untermischen.",
    thermomix: "Spinat und Erdäpfel 5 Sek./Stufe 5 zerkleinern. Wasser und Rindfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [ { food: "Rindfleisch (mager)", grams: 20 }, { food: "Spinat, gekocht", grams: 60 }, { food: "Kartoffel gekocht", grams: 5 }, { food: "Rapsöl", grams: 9 }, { food: "Wasser", grams: 40 } ],
  },
];
