// Standard-Rezepte für die ketogene Sondennahrung (ca. 20 Stück, vielfältig).
// Alle Rezepte sind so gewählt, dass sie ein Verhältnis von 1,8:1 sicher
// erreichen. Die Software rechnet jedes Rezept automatisch auf das eingestellte
// Verhältnis und die Kalorien pro Mahlzeit um.
// Felder: name, icon, ketocal, zubereitung (klassisch), thermomix (TM5), items.
const RECIPES_SONDE = [
  // ---------- Mit KetoCal ----------
  {
    name: "Obstbrei – Banane",
    icon: "🍌",
    ketocal: true,
    zubereitung: "Das kalte Wasser in einen Topf geben und das Johannisbrotkernmehl mit dem Schneebesen einrühren. Unter gelegentlichem Rühren erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann KetoCal 3:1 glatt unterrühren und Butter sowie Banane zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl in den Mixtopf geben, 8 Sek./Stufe 4 verrühren. 6 Min./90 °C/Stufe 2 andicken. Ca. 5 Min. auf 45–50 °C abkühlen lassen, dann KetoCal 3:1, Butter und Banane zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [
      { food: "Butter", grams: 4 },
      { food: "Wasser", grams: 100 },
      { food: "Johannisbrotkernmehl", grams: 2 },
      { food: "KetoCal 3:1", grams: 15 },
      { food: "Banane", grams: 20 },
    ],
  },
  {
    name: "Obstbrei – Apfelmus",
    icon: "🍎",
    ketocal: true,
    zubereitung: "Das kalte Wasser in einen Topf geben und das Johannisbrotkernmehl mit dem Schneebesen einrühren. Unter gelegentlichem Rühren erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann KetoCal 3:1 glatt unterrühren und Butter sowie Apfelmus zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl in den Mixtopf geben, 8 Sek./Stufe 4 verrühren. 6 Min./90 °C/Stufe 2 andicken. Ca. 5 Min. auf 45–50 °C abkühlen lassen, dann KetoCal 3:1, Butter und Apfelmus zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [
      { food: "Butter", grams: 3 },
      { food: "Wasser", grams: 100 },
      { food: "Johannisbrotkernmehl", grams: 2 },
      { food: "KetoCal 3:1", grams: 15 },
      { food: "Apfelmus ungesüßt", grams: 20 },
    ],
  },
  {
    name: "Obstbrei – Banane & Apfelmus",
    icon: "🍏",
    ketocal: true,
    zubereitung: "Das kalte Wasser in einen Topf geben und das Johannisbrotkernmehl mit dem Schneebesen einrühren. Unter gelegentlichem Rühren erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann KetoCal 3:1 glatt unterrühren und Butter sowie das Obst zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl in den Mixtopf geben, 8 Sek./Stufe 4 verrühren. 6 Min./90 °C/Stufe 2 andicken. Ca. 5 Min. abkühlen lassen, dann KetoCal 3:1, Butter, Banane und Apfelmus zugeben und 20 Sek./Stufe 6 glatt pürieren.",
    items: [
      { food: "Butter", grams: 10 },
      { food: "Wasser", grams: 100 },
      { food: "Johannisbrotkernmehl", grams: 2 },
      { food: "KetoCal 3:1", grams: 15 },
      { food: "Banane", grams: 20 },
      { food: "Apfelmus ungesüßt", grams: 15 },
    ],
  },
  {
    name: "Gemüse-Erdäpfelbrei (Variante 1)",
    icon: "🥔",
    ketocal: true,
    zubereitung: "Erdäpfel und Zucchini garen, mit dem Wasser und KetoCal 3:1 fein pürieren und das Rapsöl untermischen.",
    thermomix: "Gegarte Erdäpfel und Zucchini mit Wasser und KetoCal 3:1 in den Mixtopf geben, 8 Min./90 °C/Stufe 1 erwärmen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Wasser", grams: 40 },
      { food: "KetoCal 3:1", grams: 12 },
      { food: "Rapsöl", grams: 9 },
      { food: "Erdäpfel gekocht", grams: 30 },
      { food: "Zucchini gegart", grams: 50 },
    ],
  },
  {
    name: "Gemüse-Erdäpfelbrei (Variante 2)",
    icon: "🥔",
    ketocal: true,
    zubereitung: "Erdäpfel und Zucchini garen, mit dem Wasser und KetoCal 3:1 fein pürieren und das Rapsöl untermischen.",
    thermomix: "Gegarte Erdäpfel und Zucchini mit Wasser und KetoCal 3:1 in den Mixtopf geben, 8 Min./90 °C/Stufe 1 erwärmen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Wasser", grams: 40 },
      { food: "KetoCal 3:1", grams: 12 },
      { food: "Rapsöl", grams: 7 },
      { food: "Erdäpfel gekocht", grams: 30 },
      { food: "Zucchini gegart", grams: 50 },
    ],
  },
  {
    name: "Milch-Grieß-Obstbrei",
    icon: "🥣",
    ketocal: true,
    zubereitung: "Wasser mit dem Johannisbrotkernmehl verrühren und erhitzen, bis der Brei andickt. Auf 45–50 °C abkühlen lassen, dann Grießbrei und KetoCal 3:1 glatt unterrühren. Zum Schluss Butter und Apfelmus zugeben.",
    thermomix: "Wasser und Johannisbrotkernmehl in den Mixtopf geben, 8 Sek./Stufe 4 verrühren, 6 Min./90 °C/Stufe 2 andicken. Auf ~45–50 °C abkühlen lassen, dann Grießbrei, KetoCal 3:1, Butter und Apfelmus zugeben und 20 Sek./Stufe 6 glatt rühren.",
    items: [
      { food: "Wasser", grams: 120 },
      { food: "Apfelmus ungesüßt", grams: 15 },
      { food: "Himmeltau Grießbrei", grams: 5 },
      { food: "KetoCal 3:1", grams: 12 },
      { food: "Butter", grams: 11 },
      { food: "Johannisbrotkernmehl", grams: 2 },
    ],
  },
  {
    name: "Karottensuppe",
    icon: "🥕",
    ketocal: true,
    zubereitung: "Karotten und Zwiebel in Wasser oder – ganz bzw. teilweise – in klarer Gemüsebrühe weich kochen und fein pürieren. KetoCal 3:1, Schlagobers und Butter unterrühren.",
    thermomix: "Karotten und Zwiebel grob 5 Sek./Stufe 5 zerkleinern. Wasser (oder Gemüsebrühe) zugeben, 15 Min./100 °C/Stufe 1 weich garen. KetoCal 3:1, Schlagobers und Butter zugeben und 45 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Karotten", grams: 130 },
      { food: "Zwiebel, roh", grams: 5 },
      { food: "KetoCal 3:1", grams: 10 },
      { food: "Wasser", grams: 120 },
      { food: "Schlagobers (NÖM)", grams: 20 },
      { food: "Butter", grams: 6 },
    ],
  },

  // ---------- Ohne KetoCal ----------
  {
    name: "Gemüse-Fleischbrei – Zucchini",
    icon: "🥒",
    ketocal: false,
    zubereitung: "Das Gemüse abwiegen, in wenig Wasser weich dünsten und mit dem gegarten Fleisch pürieren. Anschließend das Rapsöl untermischen.",
    thermomix: "Zucchini in groben Stücken in den Mixtopf geben, 5 Sek./Stufe 5 zerkleinern. Wasser und gegartes Hühnerfleisch zugeben, 10 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Hühnerbrust ohne Haut", grams: 20 },
      { food: "Rapsöl", grams: 13 },
      { food: "Wasser", grams: 60 },
      { food: "Zucchini roh", grams: 80 },
    ],
  },
  {
    name: "Gemüse-Fleischbrei – Karotten",
    icon: "🥕",
    ketocal: false,
    zubereitung: "Das Gemüse abwiegen, in wenig Wasser weich dünsten und mit dem gegarten Fleisch pürieren. Anschließend das Rapsöl untermischen.",
    thermomix: "Karotten in Stücken 5 Sek./Stufe 5 zerkleinern. Wasser und gegartes Hühnerfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Karotten", grams: 45 },
      { food: "Hühnerbrust ohne Haut", grams: 20 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 60 },
    ],
  },
  {
    name: "Fisch-Brokkoli-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Brokkoli weich garen und mit gegartem Fisch, Wasser und Rapsöl fein pürieren.",
    thermomix: "Brokkoli in den Mixtopf geben, 5 Sek./Stufe 5 zerkleinern. Wasser zugeben, 8 Min./100 °C/Stufe 1 garen. Gegarten Fisch und Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Heilbutt, gegart", grams: 30 },
      { food: "Brokkoli, gekocht", grams: 50 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 50 },
    ],
  },
  {
    name: "Hendl-Karotten-Creme",
    icon: "🍗",
    ketocal: false,
    zubereitung: "Karotten weich garen, mit gegartem Hendl, Wasser und Rapsöl fein pürieren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Hendlbrust zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Hendlbrust ohne Haut", grams: 25 },
      { food: "Karotten, gekocht", grams: 50 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 50 },
    ],
  },
  {
    name: "Hendl-Zucchini-Creme",
    icon: "🍗",
    ketocal: false,
    zubereitung: "Zucchini weich garen, mit gegartem Hendl, Wasser und Rapsöl fein pürieren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern. Wasser und Hendlbrust zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Hendlbrust ohne Haut", grams: 25 },
      { food: "Zucchini gegart", grams: 70 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 40 },
    ],
  },
  {
    name: "Karfiol-Hendl-Creme",
    icon: "🥦",
    ketocal: false,
    zubereitung: "Karfiol weich garen, mit gegartem Hendl, Wasser und Rapsöl fein pürieren.",
    thermomix: "Karfiol 5 Sek./Stufe 5 zerkleinern. Wasser und Hendlbrust zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Hendlbrust ohne Haut", grams: 25 },
      { food: "Karfiol, gekocht", grams: 60 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 40 },
    ],
  },
  {
    name: "Pute-Karotten-Creme",
    icon: "🦃",
    ketocal: false,
    zubereitung: "Karotten weich garen, mit gegarter Putenbrust, Wasser und Rapsöl fein pürieren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Putenbrust zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Putenbrust ohne Haut", grams: 25 },
      { food: "Karotten, gekocht", grams: 50 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 50 },
    ],
  },
  {
    name: "Rindfleisch-Gemüse-Püree",
    icon: "🥩",
    ketocal: false,
    zubereitung: "Gemüse weich garen, mit gegartem Rinderhackfleisch, Wasser und Rapsöl fein pürieren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Rinderhackfleisch zugeben, 12 Min./100 °C/Stufe 1 garen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Rinderfaschiertes", grams: 25 },
      { food: "Karotten, gekocht", grams: 50 },
      { food: "Rapsöl", grams: 10 },
      { food: "Wasser", grams: 50 },
    ],
  },
  {
    name: "Forelle-Erdäpfel-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Erdäpfel garen, mit gegarter Forelle, Wasser und Rapsöl fein pürieren.",
    thermomix: "Erdäpfel grob zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Gegarte Forelle und Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Forelle, gegart", grams: 30 },
      { food: "Erdäpfel gekocht", grams: 30 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 50 },
    ],
  },
  {
    name: "Thunfisch-Zucchini-Püree",
    icon: "🐟",
    ketocal: false,
    zubereitung: "Zucchini weich garen, abgetropften Thunfisch, Wasser und Olivenöl zugeben und fein pürieren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern, Wasser zugeben, 8 Min./100 °C/Stufe 1 garen. Abgetropften Thunfisch und Olivenöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Thunfisch in Öl (Dose)", grams: 30 },
      { food: "Zucchini gegart", grams: 70 },
      { food: "Olivenöl", grams: 12 },
      { food: "Wasser", grams: 50 },
    ],
  },
  {
    name: "Erdäpfel-Gemüse-Creme",
    icon: "🥔",
    ketocal: false,
    zubereitung: "Erdäpfel und Zucchini garen, mit Wasser fein pürieren und das Rapsöl untermischen.",
    thermomix: "Gegarte Erdäpfel und Zucchini mit Wasser in den Mixtopf geben, 8 Min./90 °C/Stufe 1 erwärmen. Rapsöl zugeben und 40 Sek./Stufe 8 fein pürieren.",
    items: [
      { food: "Erdäpfel gekocht", grams: 30 },
      { food: "Zucchini gegart", grams: 50 },
      { food: "Rapsöl", grams: 12 },
      { food: "Wasser", grams: 40 },
    ],
  },
  {
    name: "Avocado-Hendl-Creme",
    icon: "🥑",
    ketocal: false,
    zubereitung: "Hendl und Karotten garen, mit Avocado, Wasser und Rapsöl fein pürieren.",
    thermomix: "Karotten 5 Sek./Stufe 5 zerkleinern. Wasser und Hendlbrust zugeben, 12 Min./100 °C/Stufe 1 garen. Avocado und Rapsöl zugeben und 40 Sek./Stufe 7 cremig pürieren.",
    items: [
      { food: "Hendlbrust ohne Haut", grams: 30 },
      { food: "Avocado", grams: 20 },
      { food: "Karotten, gekocht", grams: 40 },
      { food: "Rapsöl", grams: 6 },
      { food: "Wasser", grams: 40 },
    ],
  },
  {
    name: "Ei-Gemüse-Creme",
    icon: "🥚",
    ketocal: false,
    zubereitung: "Ei hart kochen, mit gegarter Zucchini, Wasser und Rapsöl fein pürieren.",
    thermomix: "Zucchini 5 Sek./Stufe 5 zerkleinern, mit Wasser 8 Min./100 °C/Stufe 1 garen. Geschältes hart gekochtes Ei und Rapsöl zugeben und 30 Sek./Stufe 7 cremig pürieren.",
    items: [
      { food: "Hühnerei, Vollei, frisch", grams: 40 },
      { food: "Zucchini gegart", grams: 60 },
      { food: "Rapsöl", grams: 8 },
      { food: "Wasser", grams: 40 },
    ],
  },
];
